# Site settings
title: QA - Juan Garcia
email: juangarciamarinblog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "juangarciamarin.com" # the base hostname & protocol for your site

twitter_username:
github_username: juangm
linkedin_username: juangm

# Build settings
markdown: kramdown
